networks:
  network-zabbix:
    driver: bridge

services:
  mysql:
    container_name: mysql
    image: mysql
    user: root
    networks:
      - network-zabbix
    ports:
      - '3000:3306'
    volumes:
      - './db/mysql:/var/lib/data'
    environment:
      - MYSQL_ROOT_PASSWORD=devops
      - MYSQL_DATABASE=db
      - MYSQL_USER=db
      - MYSQL_PASSWORD=devops

  zabbix-server:
    container_name: zabbix-server
    image: zabbix/zabbix-server-mysql:5.0-ubuntu-latest
    networks:
      - network-zabbix
    links:
      - mysql
    restart: always
    ports:
      - '10051:10051'
    volumes:
      - './zabbix/alertscripts:/usr/lib/zabbix/alertscripts'
    environment:
      - DB_SERVER_HOST=mysql
      - DB_SERVER_PORT=3306
      - MYSQL_DATABASE=db
      - MYSQL_USER=db
      - MYSQL_PASSWORD=devops
    depends_on:
      - mysql

  zabbix-frontend:
    container_name: zabbix-frontend
    image: zabbix/zabbix-web-apache-mysql:5.0-ubuntu-latest
    networks:
      - network-zabbix
    restart: always
    ports:
      - '80:8080'
    environment:
      - DB_SERVER_HOST=mysql
      - DB_SERVER_PORT=3306
      - MYSQL_DATABASE=db
      - MYSQL_USER=db
      - MYSQL_PASSWORD=devops
      - PHP_TZ=Africa/Casablanca
    depends_on:
      - mysql

  zabbix-agent:
    container_name: zabbix-agent
    image: zabbix/zabbix-agent2:5.0-ubuntu-latest
    user: root
    networks:
      - network-zabbix
    links:
      - zabbix-server
    restart: always
    privileged: true
    volumes:
      - /var/run:/var/run
    ports:
      - '10050:10050'
    environment:
      - ZBX_HOSTNAME=Zabbix server
      - ZBX_SERVER_HOST=host.docker.internal
    
  grafana:
    container_name: grafana
    image: grafana/grafana:latest
    networks:
      - network-zabbix
    links:
      - mysql
      - zabbix-server
    restart: always
    ports:
      - '3001:3000'
    environment: 
      - GF_INSTALL_PLUGINS=alexanderzobnin-zabbix-app
    depends_on:
      - mysql
      - zabbix-server